[package]
name = "motionsensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pir-motion-sensor = "0.1.2"
rascam = "0.0.2"
tokio = { version = "1.27.0", features = ["full"] }
